### ISSUE TITLE
feat: convergence criteria

### ISSUE THREAD

**Issue by AdrianM0** [AustinT/mol_ga#11]
Hi @AustinT, thanks for the nice package, I was wondering if you could add an option for a convergence criterion? If this is already present in the package, would be great to know how to enable it?

Say something like this:

```python
CRITERION  = 1
if any(y > CRITERION for y in list_of_scores):
	stop_program()
```

**Comment by AustinT** [comment]
Hi @AdrianM0, early stopping is not something I explicitly put into the GA loop (I wanted to keep it simple). If you want this behaviour I suggest you just run the GA one iteration at a time, essentially:

```python
# Instead of this
run_ga_maximization(
  max_generations=100,
  [...]
)

# Do this
for gen in range(100):
  res = run_ga_maximization(
    max_generations=1,
   )
if ([... something based on res]):
  break
```

This should work because the default GA is stateless (the set-up at the beginning should not affect the results). However, to avoid duplicate evaluations of your objective function, you should wrap your objective in a `CachedBatchFunction` (something which is done internally anyway). Here is a full code sample (assuming the default GA):

```python
CRITERION = 1. # as you wrote
objective = CachedBatchFunction(original_objective)
start_population_smiles = [...]. # whatever this was before
for i in range(max_generations):  # assuming this is defined elsewhere
  res = default_ga(
     max_generations=1,
    starting_population_smiles=starting_population_smiles,
     scoring_function=objective,
     **kwargs
  )
  # (note that all evals will be stored in the cache of `objective`)

  # Evaluate your criterion
  if any(y > CRITERION for y, _ in res.population):
    break
  else:
    start_population_smiles = [s for _, s in res.population]. # carry over population to next generation
```

Does this solve your issue?

**Comment by AdrianM0** [comment]
@AustinT oh, this is a great idea actually, thanks for the suggestion.
I will close the issue now.

**Comment by UnixJunkie** [comment]
You could use collapse of the population's diversity as a stop criterion. Cf. https://github.com/UnixJunkie/FASMIFRA/blob/main/bin/fasmifra_GA.sh

**Comment by AustinT** [comment]
> You could use collapse of the population's diversity as a stop criterion. Cf. https://github.com/UnixJunkie/FASMIFRA/blob/main/bin/fasmifra_GA.sh

Technically the collapse of diversity does not actually mean that the algorithm has converged (mutations can still introduce meaningful novelty into a population with collapsed diversity).
